FROM python:3.13.1-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

# Create static and media directories
RUN mkdir -p /app/static /app/media \
    && chmod -R 755 /app/static /app/media

RUN DJANGO_SETTINGS_MODULE=core.settings-prod python manage.py collectstatic --noinput
